import mongoose from 'mongoose'

const Schema=mongoose.Schema;
let Realestate=new Schema({
    _id:{
        type:String
    },
    Realestate :
    {
        Name:{
            type:String
        },
        City:{
            type:String
        },
        Municipality:{
            type:String
        },
        Microlocation:{
            type:String
        },
        Street:{
            type:String
        },
        Area:{
            type:Number
        },
        Rooms:{
            type:Number
        },
        ConstructionYear:{
            type:Number
        },
        State:{
            type:String
        },
        Heating:{
            type:String
        },
        Floor:{
            type:Number
        },
        TotalFloors:{
            type:Number
        },
        Parking:{
            type:String
        },
        MonthlyUtilities:{
            type:Number
        },
        Price:{
            type:Number
        },
        About:{
            type:String
        },
        Sold:{
            type:String
        },
        DateSold:{
            type:String
        },
        LastModified:{
            type:String
        },
        Characteristics:{
            type:Array
        },
        Bus:{
            type:Array
        }
    },
    Advertiser:{
        type:Array
    },
    Pictures:{
        type:Array
    }   
})
export default mongoose.model('Realestate',Realestate,'estate')